name: CD on develop branch

on:
  push:
    branches: [ "develop" ]
    paths:
      - 'backend/**'

jobs:
  deploy-to-ec2:
    name: Deploy to EC2
    runs-on: [ self-hosted ]

    defaults:
      run:
        working-directory: backend/spring-routie

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build Spring Boot Jar
        run: ./gradlew clean bootJar

      - name: Restore application.yml (external to jar)
        run: |
          mkdir -p config
          echo "${{ secrets.APPLICATION_YML_PROD }}" > config/application.yml

      - name: Kill existing Spring Process
        run: |
          PID=$(lsof -ti:8080 || true)
          if [ -n "$PID" ]; then
            echo "Killing process on port 8080: $PID"
            kill -9 "$PID"
          else
            echo "No process found on port 8080"
          fi

      - name: Start Spring Boot Application with external config
        run: |
          JAR_NAME=$(ls build/libs/*.jar | head -n 1)
          nohup java -jar "$JAR_NAME" --spring.config.location=./config/application.yml > app.log 2>&1 &
          echo "Started $JAR_NAME with external config"
